name: 'setup-action-ruby2.1.2'
description: 'setup ruby 2.1.2'
runs:
  using: "composite"
  steps: 
    - name: Setup Libs
      run: |
        # remove MySQL5.7
        mysql --version
        sudo apt-get remove --purge mysql-server mysql-client mysql-common && sudo apt-get autoremove && sudo apt-get autoclean && sudo deluser mysql && sudo rm -rf /var/lib/mysql && sudo apt-get purge mysql-server-core-5.7 && sudo apt-get purge mysql-client-core-5.7 && sudo rm -rf /var/log/mysql && sudo rm -rf /etc/mysql
        # sudo apt-get purge mysql-server*
        sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu trusty universe'
        sudo apt-get update


        # Install apt
        sudo apt-get install autoconf bison build-essential gcc-6 g++-6 libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm-dev mysql-server-5.6 mysql-client-5.6
        # sudo apt-get install autoconf bison build-essential gcc-6 g++-6 libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm5 libgdbm-dev mysql-server mysql-client libmysqlclient-dev
        # mysql --version        

        # Install libmysqlclient5.6
        mkdir -p ~/.src/libmysqlclient
        cd ~/.src/libmysqlclient
        wget http://launchpadlibrarian.net/212189159/libmysqlclient18_5.6.25-0ubuntu1_amd64.deb
        wget http://launchpadlibrarian.net/212189147/libmysqlclient-dev_5.6.25-0ubuntu1_amd64.deb
        cd ~/.src/libmysqlclient
        sudo dpkg -i libmysqlclient18_5.6.25-0ubuntu1_amd64.deb
        sudo dpkg -i libmysqlclient-dev_5.6.25-0ubuntu1_amd64.deb
      shell: bash
